baseurl = "/"
languageCode = "en-gb"
languageLang = "en-gb"
title = "NeoSki"
enableRobotsTXT = true
[outputs]
  home = ["HTML", "RSS", "MARKDOWN", "LLMSTXT"]
  page = ["HTML", "MARKDOWN", "LLMSTXT"]
  term = ["HTML", "MARKDOWN"]
[outputFormats]
  [outputFormats.markdown]
    name = "markdown"
    baseName = "index"
    mediaType = "text/markdown"
    isPlainText = true
  [outputFormats.LLMSTXT]
  mediaType = "text/plain"
  baseName = "llms"
  isPlainText = true
  notAlternative = true
[taxonomies]
  tag = 'tags'
  topic = 'topics'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true