baseurl = "/"
languageCode = "en-gb"
languageLang = "en-gb"
title = "NeoSki"
enableRobotsTXT = true
[outputs]
  home = ["html", "rss", "markdown", "llms"]
[outputFormats]
  [outputFormats.markdown]
    name = "markdown"
    baseName = "index"
    mediaType = "text/markdown"
    isPlainText = true
  [outputFormats.llms]
    baseName = "llms"
    isPlainText = true
    mediaType = "text/plain"
    rel = "alternate"
    root = true
[taxonomies]
  tag = 'tags'
  topic = 'topics'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]